MobileAds.podspec
MobileAds.xcodeproj/project.pbxproj
MobileAds/AdMob/AdNative/Medium/MediumNativeAdView.swift
MobileAds/AdMob/AdNative/Small/SmallNativeAdView.swift
MobileAds/AdMob/AdNative/Unified/UnifiedNativeAdView.swift
MobileAds/AdMob/AdResume/AdResumeManager.swift
MobileAds/AdMob/Constants/ConstantsAds.swift
MobileAds/AdMob/Constants/Utils.swift
MobileAds/AdMob/Manager/AdMobManager+Interstitial.swift
MobileAds/AdMob/Manager/AdMobManager+Native.swift
MobileAds/AdMob/Manager/AdMobManager+Rewarded.swift
MobileAds/AdMob/Manager/AdMobManager.swift
Podfile
Podfile.lock

[Update] Update admob

---

MobileAds/AdMob/AdResume/AdResumeManager.swift
MobileAds/AdMob/Manager/AdMobManager+Interstitial.swift

[Update] Add resume id and update

---

MobileAds/AdMob/AdNative/Medium/MediumNativeAdView.swift
MobileAds/AdMob/AdNative/Medium/MediumNativeAdView.xib
MobileAds/AdMob/AdNative/Small/SmallNativeAdView.swift
MobileAds/AdMob/AdNative/Unified/UnifiedNativeAdView.swift
MobileAds/AdMob/Manager/AdMobManager+Native.swift
MobileAds/AdMob/Manager/AdMobManager.swift

[Update] Update UI

---

MobileAds/AdMob/AdNative/Medium/MediumNativeAdView.xib

[Update] Update border ad native

---

MobileAds/AdMob/Manager/AdMobManager.swift

[Update] Set public to remove ad

---

MobileAds/AdMob/Extension/UIViewControll+Extension+Ads.swift
MobileAds/AdMob/Manager/AdMobManager+Interstitial.swift

[Update] Fix leak memory + indicator

---

MobileAds/RemoteConfig/RemoteConfigService.swift

- Update Remote Config Service

[Update] Update Remote Config Service

---

MobileAds/AdMob/AdResume/AdResumeManager.swift

- Add loading vc to key window ad resume

[Update] Add loading vc to key window ad resume

---

MobileAds/AdMob/Manager/AdMobManager+Rewarded.swift
MobileAds/AdMob/Manager/AdMobManager.swift

[Update] Fix bug reward

---

MobileAds/RemoteConfig/RemoteConfigService.swift

- Add parse json remote config function

[Update] Add parse json remote config function

---

MobileAds/AdMob/Manager/AdMobManager+Banner.swift

- Custom banner sketeton view color

[Update] Custom banner sketeton view color

---

MobileAds/AdMob/AdResume/AdResumeManager.swift
MobileAds/AdMob/Manager/AdMobManager+Banner.swift
MobileAds/AdMob/Manager/AdMobManager+Interstitial.swift
MobileAds/AdMob/Manager/AdMobManager.swift

- Add click callback except native ad

[Update] Add click callback except native ad

---

MobileAds/AdMob/AdNative/Medium/MediumNativeAdView.xib

- Fix space button medium native ad

[Update] Fix space button medium native ad

---

MobileAds/AdMob/AdNative/Medium/MediumNativeAdView.xib
MobileAds/AdMob/AdNative/Unified/Option_1/UnifiedNativeAdView.xib
MobileAds/AdMob/AdNative/Unified/Option_2/UnifiedNativeAdView_2.xib

[Update] Update ad label

---

MobileAds/AdMob/AdInterstitial/AdFullScreenLoadingVC.swift
MobileAds/AdMob/AdResume/AdResumeManager.swift

- Add resume ad loading string

[Update] Add resume ad loading string

---

MobileAds/AdMob/AdResume/AdResumeManager.swift

- Update ad resume loading string

[Update] Update ad resume loading string

---

MobileAds/AdMob/Manager/AdMobManager+Interstitial.swift

- Fix case auto dismiss inter -> show resume

[Update] Fix case auto dismiss inter -> show resume

---

MobileAds/AdMob/Manager/AdMobManager+Interstitial.swift

[Update] Fix showing ad resume

---

MobileAds/AdMob/Manager/AdMobManager+Interstitial.swift

- Update block did dismiss ad interstitial

Update block did dismiss ad interstitial

---

MobileAds/AdMob/Manager/AdMobManager+Native.swift

Fix ad native

---

MobileAds/AdMob/AdNative/Unified/Option_2/UnifiedNativeAdView_2.swift
MobileAds/AdMob/AdNative/Unified/Option_2/UnifiedNativeAdView_2.xib
MobileAds/AdMob/Constants/Utils.swift
MobileAds/AdMob/Manager/AdMobManager.swift

Update unified native ad 2

---

MobileAds/AdMob/AdNative/Medium/MediumNativeAdView.swift
MobileAds/AdMob/AdNative/Small/SmallNativeAdView.swift
MobileAds/AdMob/AdNative/Unified/Option_1/UnifiedNativeAdView.swift
MobileAds/AdMob/AdNative/Unified/Option_1/UnifiedNativeAdView.xib

Update label ad

---

MobileAds/AdMob/AdNative/FreeSize/FreeSizeNativeAdView.swift
MobileAds/AdMob/AdNative/Unified/Option_1/UnifiedNativeAdView.xib

- [Fix bug] Color label ads
- [IVP-1155](https://jira.apero.vn/browse/IVP-1155)

[Fix bug] Color label ads

---

MobileAds/AdMob/AdNative/FreeSize/FreeSizeNativeAdView.swift
MobileAds/AdMob/AdNative/FreeSize/FreeSizeNativeAdView.xib

- [Update] Update style freesize ad

[Update] Update style freesize ad

---

MobileAds/AdMob/AdNative/Medium/MediumNativeAdView.swift
MobileAds/AdMob/AdNative/Medium/MediumNativeAdView.xib
MobileAds/AdMob/Manager/AdMobManager.swift

Custom button height

---

MobileAds/AdMob/Manager/AdMobManager.swift

Add banner sample id

---

MobileAds/AdMob/Manager/AdMobManager+Interstitial.swift

Fix interstitial

---

MobileAds/AdMob/AdNative/FreeSize/FreeSizeNativeAdView.swift
MobileAds/AdMob/AdNative/FullCreen/FullScreenNativeAdView.xib

update button and ad label

---

MobileAds/AdMob/Manager/AdMobManager.swift

- Change ads event tracking name

Change ads event tracking name
